### PR TITLE
Update Chainguard source

### PR DESCRIPTION
**Pull request by oliverchang**
This contains both Chainguard and wolfi.

### CODE REVIEW

**Review by andrewpollock — APPROVED** [review]
This will leave existing records orphaned, right?

**Comment by oliverchang** [comment]
> This will leave existing records orphaned, right?

Yeah, those will have to be cleaned up manually I think.

**Comment by cpanato** [comment]
Is there anything that I can do to help?

**Comment by oliverchang** [comment]
> Is there anything that I can do to help?

Should be all good :) Will let you know if anything comes up!

**Pull request merged**
