### PR TITLE
Mobile View #1803

### PR DESCRIPTION
**Pull request by mustafaazad03**
Issue solved: #1803 
Mobile View : Columns in list are not fully visible
### Preview : 

https://github.com/google/osv.dev/assets/97380192/754665af-4ef4-4fde-a12c-bf891eb413b6

### CODE REVIEW

**Comment by andrewpollock** [comment]
Please see https://github.com/google/osv.dev/issues/1803#issuecomment-1925973832

**Review by another-rex — COMMENTED** [review]
Thanks! Can you also remove the mentions of hide-on-mobile class in list.html?

**Comment by another-rex** [comment]
> Thanks! Can you also remove the mentions of hide-on-mobile class in list.html?

Just bumping this message, once that's removed, we should be able to merge this!

**Comment by mustafaazad03** [comment]
Hi @another-rex, sorry for the delay but yeah I remove the traces. Please review and let me know if any changes are there.

**Review by another-rex — APPROVED** [review]

**Pull request merged**
