### PR TITLE
Add SBOMResearcher to third-party.md

### PR DESCRIPTION
**Pull request by bigdawgsfootball**
Add reference to SBOMResearcher PS tool.

Thanks for making OSV.dev, it's awesome!

### CODE REVIEW

**Comment by cuixq** [comment]
Hi @bigdawgsfootball, we are now asking all new projects that we link to consider adopting [OpenSSF Scorecard](https://scorecard.dev/#using-the-github-action) as a signal of their open source security practices.

**Comment by bigdawgsfootball** [comment]
I think that's a good idea, and have already added it to my repo.

**Comment by bigdawgsfootball** [comment]
Current scores are below:
image

**Comment by andrewpollock** [comment]
Hi @bigdawgsfootball I'm sorry to be the bearer of bad news, but we decided our list of third-party integrations was getting too long to maintain, and have changed direction on what we're linking out to. As such, we won't be merging this PR.

**Comment by bigdawgsfootball** [comment]
Sadness... Fair enough, thanks for the heads up.

**Pull request closed without merging**
