### PR TITLE
feat(sources): add Red Hat to Production

### PR DESCRIPTION
**Pull request by andrewpollock**

### CODE REVIEW

**Comment by andrewpollock** [comment]
@jasinner FYI

**Comment by andrewpollock** [comment]
Current blockers to merging:

- [ ] Versions in Purls (makes API querying by Purl non-functional)
- [ ] Architectures in versions (causes incorrect version sorting behaviour)

**Comment by andrewpollock** [comment]
Individual record existence based on a snapshot of https://security.access.redhat.com/data/osv/all.json from earlier today checked out 100% 👍

**Review by oliverchang — APPROVED** [review]
woohoo!

**Comment by andrewpollock** [comment]
https://github.com/ossf/osv-schema/pull/294 addresses both of the blocking issues, so once it has been validated, and the data regenerated and reviewed in Staging, this should be good to merge.

**Pull request merged**
