### PR TITLE
docs(faq): reorganise by category

### PR DESCRIPTION
**Pull request by andrewpollock**
Break the FAQ into 4 broad categories:

- background
- usage
- data
- infrastructure

and place the existing entries under these.

Address various markdownlint complaints and a config file to disable
- line length
- embedded HTML

### CODE REVIEW

**Comment by another-rex** [comment]
You can host a preview version of the docs by changing the branch in your fork repository that github pages publish. E.g. https://github.com/andrewpollock/osv.dev/settings/pages

**Comment by andrewpollock** [comment]
> You can host a preview version of the docs by changing the branch in your fork repository that github pages publish. E.g. https://github.com/andrewpollock/osv.dev/settings/pages

Thanks, https://andrewpollock.github.io/osv.dev/faq/ has it but the rendering is weird...

**Comment by another-rex** [comment]
That does look odd.. Are your settings same as here? https://github.com/google/osv.dev/settings/pages (except with a different branch)

**Comment by andrewpollock** [comment]
> That does look odd.. Are your settings same as here? https://github.com/google/osv.dev/settings/pages (except with a different branch)

Ah, I had it set to the root instead of `/docs`. Now, how to force a republish? Push a no-op commit I guess?

**Comment by andrewpollock** [comment]
https://andrewpollock.github.io/osv.dev/faq/ is looking more like intended

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
