### PR TITLE
Validate 'link' attribute has the ending '/'

### PR DESCRIPTION
**Pull request by jess-lowe**

### CODE REVIEW

**Review by andrewpollock — APPROVED** [review]
LGTM, thanks!

Are there any other opportunities for validation? This code is still going to be run post-merge, though right? So while it's stopping the rot from propagating further down the pipeline, it's not stopping it from being checked in in the first place.

**Comment by jess-lowe** [comment]
> LGTM, thanks!
> 
> Are there any other opportunities for validation? This code is still going to be run post-merge, though right? So while it's stopping the rot from propagating further down the pipeline, it's not stopping it from being checked in in the first place.

Yeah true, maybe I can add a testcase to check for it so we know the build will fail before it merges?

**Comment by another-rex** [comment]
Oh oops

**Comment by another-rex** [comment]
Can you retarget this to

**Pull request merged**
