### PR TITLE
Made website responsive

### PR DESCRIPTION
**Pull request by mustafaazad03**
# Pull Request

## Description

I made changes in css file where I added the word wrap so that the overflow of pre tag is solved and I test it on the site as well so that this will not cause any errors further. Issue #1741  .

## Changes Made

Added the two lines in css ->
overflow-x: scroll;
  width: 100%;

## Screenshots
image

 

## Checklist

- [x] I have reviewed the [contribution guidelines](CONTRIBUTING.md) for this project.
- [x] I have read the [code of conduct](CODE_OF_CONDUCT.md) for this project.
- [x] My code follows the coding style of this project.
- [x] My changes generate no new warnings or errors.
- [x] I have tested this code and confirmed that it works as expected.

## Related Issues

I fixed issue related to #1741 i.e Responsiveness of osv.dev website 

## Reviewers

@hogo6002

### CODE REVIEW

**Review by another-rex — APPROVED** [review]
Thanks! Can you have a look at the CLA checker and accept the agreement then we can get this merged!

**Comment by mustafaazad03** [comment]
Hi @another-rex ,
I have done the cla check.

**Pull request merged**
