### PR TITLE
Update hugo and remove ^ from version

### PR DESCRIPTION
**Pull request by another-rex**
Attempt to update hugo and see if that helps it build.

### CODE REVIEW

**Review by michaelkedar — APPROVED** [review]
The ci and deployment images need to be manually built & pushed

**Comment by another-rex** [comment]
Hmm can't even build it, I think we need a newer version of go, I'll test that out

**Comment by andrewpollock** [comment]
> Hmm can't even build it, I think we need a newer version of go, I'll test that out

The path of least resistance might be to revert the config file rename for now?

**Comment by another-rex** [comment]
Latest version of go fixed the build issue, but yeah, I think changing the go version might be too risky for a blog post change, and should be separate.

**Comment by another-rex** [comment]
Found a nice middleground, updated hugo to 0.111.3, which is what I have running locally, so I know it works, and it compiles with our current version of go.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
