### PR TITLE
OSV4K: Java/Kotlin serialization library for OSV

### PR DESCRIPTION
**Pull request by akuleshov7**
### What's done:
- added a [link to a common serialization library](https://github.com/saveourtool/osv4k) of OSV for Kotlin MPP (via kotlinx.serialization) and Java (via Jackson)

### CODE REVIEW

**Comment by akuleshov7** [comment]
@andrewpollock @oliverchang can you please have a look? It's just a very small documentation change

**Review by andrewpollock — APPROVED** [review]
Thanks for the contribution

**Comment by akuleshov7** [comment]
@andrewpollock CI passed, let’s merge? 🥰

**Pull request merged**
