### PR TITLE
Adding Betterscan CE to "Third party tools and integrations" section

### PR DESCRIPTION
**Pull request by marcinguy**
Betterscan CE is a Code Scanning/SAST/Static Analysis/Linting using many tools/Scanners with One Report (Code, IaC). Supports major programming and Cloud stacks.

Now with added OSV Scanner it will scan SBOM and dependencies vulnerabilities.

Great work!

More in the project repo and website.

Feel free to contact me in case of any questions.

Thanks,

P.S Maybe you can sort the list alphabetically

### CODE REVIEW

**Comment by andrewpollock** [comment]
> P.S Maybe you can sort the list alphabetically

Ack. Historically the list was chronological, but now that it's getting longer, I think alphabetical makes more sense. WDYT, @oliverchang ?

**Comment by andrewpollock** [comment]
Thanks for your contribution, would you mind if we send a PR to hyperlink to OSV Scanner at https://github.com/marcinguy/betterscan-ce/blob/45bb5c91fd74a1c96b2694e37903c9b5479800ae/README.md?plain=1#L487?

**Comment by andrewpollock** [comment]
@marcinguy I've got https://github.com/google/osv.dev/pull/939 out to fix the failing integration test, once that's merged you'll need to sync your fork.

**Comment by marcinguy** [comment]
> Thanks for your contribution, would you mind if we send a PR to hyperlink to OSV Scanner at https://github.com/marcinguy/betterscan-ce/blob/45bb5c91fd74a1c96b2694e37903c9b5479800ae/README.md?plain=1#L487?

Yes, sure.

Will re-sync my fork after merge of #939

**Comment by andrewpollock** [comment]
https://github.com/marcinguy/betterscan-ce/pull/78

**Review by andrewpollock — APPROVED** [review]

**Pull request merged**
