### PR TITLE
Standardise on the same version of the Go buildchain as the CI image

### PR DESCRIPTION
**Pull request by andrewpollock**
Until we arrive at a "one buildchain image to rule them all" solution, to avoid Go buildchain skew, lock everything, everywhere (manually ☹) to 1.21

### CODE REVIEW

**Comment by andrewpollock** [comment]
@another-rex do you want me to give

[./vulnfeeds/cmd/alpine/Dockerfile:FROM golang:alpine AS GO_BUILD](https://github.com/google/osv.dev/blob/07d0f5dda0f3ce244970f6bb7e880a7bce52b656/vulnfeeds/cmd/alpine/Dockerfile#L15)
and
[./vulnfeeds/cmd/combine-to-osv/Dockerfile:FROM golang:alpine AS GO_BUILD](https://github.com/google/osv.dev/blob/07d0f5dda0f3ce244970f6bb7e880a7bce52b656/vulnfeeds/cmd/combine-to-osv/Dockerfile#L15)

while I'm at it?

**Comment by another-rex** [comment]
> @another-rex do you want me to give
> 
> https://github.com/google/osv.dev/blob/07d0f5dda0f3ce244970f6bb7e880a7bce52b656/vulnfeeds/cmd/alpine/Dockerfile#L15
> 
> 
> and
> https://github.com/google/osv.dev/blob/07d0f5dda0f3ce244970f6bb7e880a7bce52b656/vulnfeeds/cmd/combine-to-osv/Dockerfile#L15
> 
> the same treatment while I'm at it?

Yep, go for it.

Go 1.21 released yesterday, since we are changing the version do we want to just jump to the latest version while we are at it? It does have some nice new features/standard library additions.

**Comment by andrewpollock** [comment]
> Go 1.21 released yesterday, since we are changing the version do we want to just jump to the latest version while we are at it? It does have some nice new features/standard library additions.

I'm ambivalent. I'll need to update the CI image again to reflect that if that's the consensus?

**Comment by andrewpollock** [comment]
> Yep, go for it.

Done in 841bdd8

**Review by michaelkedar — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
