### PR TITLE
Remove local_ssd_count, and convert to ssd

### PR DESCRIPTION
**Pull request by another-rex**
Works when running apply locally.

### CODE REVIEW

**Review by michaelkedar — APPROVED** [review]
Looking at the indexer kubernetes files in `osv-config`, I can't tell if the indexer was even using the local SSDs

**Comment by another-rex** [comment]
I think the ssd is mounted to /tmp, which is used to clone/copy the repositories that are being analysed.

**Comment by oliverchang** [comment]
Note that local SSDs are a fair bit faster than pd-ssd: https://cloud.google.com/compute/docs/disks#localssds

Does this have any performance implications for us?

**Comment by another-rex** [comment]
Ohh, I got mixed up persistent disks and local ssds mixed up. 

@michaelkedar I see what you mean now, I don't see the configs using the local disk either. Maybe it automatically uses local ssds when they are available? 

> Does this have any performance implications for us?

Yes and no? This should be faster than what is currently being used (just standard persistent hard disks I believe, since no requests specifically for the ephemeral ssds), but we would probably get a speed boost by switching to using local ssds. I'll look into configuring it.

**Pull request merged**
