### PR TITLE
chore: Remove deprecated setup.py and fix license

### PR DESCRIPTION
**Pull request by another-rex**
Remove setup.py as it is unnecessary, as pyproject.toml is a superset of it.

Also fix the license, not sure why it was labelled MIT, when all our license files and headers are Apache-2.0.

### CODE REVIEW

**Review by andrewpollock — APPROVED** [review]
/cc @calebbrown woohoo!

**Comment by calebbrown** [comment]
Great work! 😁

**Review by oliverchang — APPROVED** [review]
nice! are we able to check if https://github.com/google/osv.dev/blob/master/.github/workflows/publish-to-pypi.yaml still works with this?

**Comment by another-rex** [comment]
I manually ran the command (build) with setup.py deleted and it created the same files as when setup.py were present.

**Pull request merged**
